In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error

HORIZON = 96          
FREQ = "15min"

df = pd.read_excel("../data/Elec-train.xlsx")
df

                Timestamp  Power (kW)  Temp (C°)
0     2010-01-01 01:15:00       165.1  10.555556
1           1/1/2010 1:30       151.6  10.555556
2           1/1/2010 1:45       146.9  10.555556
3           1/1/2010 2:00       153.7  10.555556
4           1/1/2010 2:15       153.8  10.555556
...                   ...         ...        ...
4790      2/19/2010 22:45         NaN  11.111111
4791      2/19/2010 23:00         NaN  11.111111
4792      2/19/2010 23:15         NaN  10.000000
4793      2/19/2010 23:30         NaN  10.000000
4794      2/19/2010 23:45         NaN  10.000000

[4795 rows x 3 columns]

In [5]:

df.columns = [c.lower().strip() for c in df.columns]

datetime_col = [c for c in df.columns if "date" in c or "time" in c][0]

df[datetime_col] = pd.to_datetime(df[datetime_col])
df = df.set_index(datetime_col).sort_index()

df.head()

                     power (kw)  temp (c°)
timestamp
2010-01-01 01:15:00       165.1  10.555556
2010-01-01 01:30:00       151.6  10.555556
2010-01-01 01:45:00       146.9  10.555556
2010-01-01 02:00:00       153.7  10.555556
2010-01-01 02:15:00       153.8  10.555556