In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error

HORIZON = 96          
FREQ = "15min"

df = pd.read_excel("../data/Elec-train.xlsx")
df

                Timestamp  Power (kW)  Temp (C°)
0     2010-01-01 01:15:00       165.1  10.555556
1           1/1/2010 1:30       151.6  10.555556
2           1/1/2010 1:45       146.9  10.555556
3           1/1/2010 2:00       153.7  10.555556
4           1/1/2010 2:15       153.8  10.555556
...                   ...         ...        ...
4790      2/19/2010 22:45         NaN  11.111111
4791      2/19/2010 23:00         NaN  11.111111
4792      2/19/2010 23:15         NaN  10.000000
4793      2/19/2010 23:30         NaN  10.000000
4794      2/19/2010 23:45         NaN  10.000000

[4795 rows x 3 columns]

In [10]:
df.shape

(4795, 3)

In [12]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4795 entries, 0 to 4794
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Timestamp   4795 non-null   datetime64[us]
 1   Power (kW)  4699 non-null   float64
 2   Temp (C°)   4795 non-null   float64
dtypes: datetime64[us](1), float64(2)
memory usage: 112.5 KB

In [15]:
df.describe()

                 Timestamp   Power (kW)    Temp (C°)
count                 4795  4699.000000  4795.000000
mean   2010-01-26 00:30:00   231.225984    10.931989
min    2010-01-01 01:15:00     0.000000     3.888889
25%    2010-01-13 12:52:30   163.100000     8.888889
50%    2010-01-26 00:30:00   253.600000    11.111111
75%    2010-02-07 12:07:30   277.700000    12.777778
max    2010-02-19 23:45:00   355.100000    19.444444
std                    NaN    58.667173     2.717175